services:

    db:
        build:
            context: .
            dockerfile: ./docker/postgres/Dockerfile
        container_name: postgres_vectors
        restart: always
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: postgres_vector_db
        volumes:
            - postgres_data:/var/lib/postgresql/data
        ports:
            - "5432:5432"

    model_1:
        build:
            context: .
            dockerfile: ./docker/model1/Dockerfile
        container_name: embedding_model
        volumes:
            - ./volumes/model:/app/model
        depends_on:
            - db

    model_2:
        build:
            context: .
            dockerfile: ./docker/model2/Dockerfile
        container_name: llm_model
        volumes:
            - ./volumes/model:/app/model
        depends_on:
            - model_1

    api:
        build:
            context: .
            dockerfile: ./docker/python/Dockerfile
        container_name: fastapi
        ports:
            - "8000:8000"
        depends_on:
            - model_2
        environment:
            DATABASE_URL: postgres://postgres:postgres@db:5432/postgres_vector_db
        volumes:
            - ./app:/app
            - ./volumes/model:/model

volumes:
    postgres_data:
